nntk: Backprop.o Bias.o Delta.o functional.o Instance.o Label.o Layer.o main.o Model.o Neuron.o Par.o Weights.o
	g++ Backprop.o Bias.o Delta.o functional.o Instance.o Label.o Layer.o main.o Model.o Neuron.o Par.o Weights.o -o nntk
Backprop.o: Backprop.cpp
	g++ -c Backprop.cpp -o Backprop.o
Bias.o: Bias.cpp
	g++ -c Bias.cpp -o Bias.o
Delta.o: Delta.cpp
	g++ -c Delta.cpp -o Delta.o
functional.o: functional.cpp
	g++ -c functional.cpp -o functional.o
Instance.o: Instance.cpp
	g++ -c Instance.cpp -o Instance.o
Label.o: Label.cpp
	g++ -c Label.cpp -o Label.o
Layer.o: Layer.cpp
	g++ -c Layer.cpp -o Layer.o
main.o: main.cpp
	g++ -c main.cpp -o main.o
Model.o: Model.cpp
	g++ -c Model.cpp -o Model.o
Neuron.o: Neuron.cpp
	g++ -c Neuron.cpp -o Neuron.o
Par.o: Par.cpp
	g++ -c Par.cpp -o Par.o
Weights.o: Weights.cpp
	g++ -c Weights.cpp -o Weights.o